mvdaisy/api/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import (CustomUserViewSet,
                    ExpertsView,
                    ExpertRetriveView,
                    RankListView,
                    RankTypeListView,
                    ExpertsInLab,
                    ExpertiseAreaInLab,
                    RemoveExpertFromLab,
                    RemoveExpertiseAreaFromLab,
                    ExpertsNotAssignedToLab,
                    AddExpertToLab,
                    )

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', CustomUserViewSet)


urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    path('experts/<int:pk>/', ExpertRetriveView.as_view(), name='expert'),
    path('experts/', ExpertsView.as_view(), name='experts'),
    path('ranks/<int:type_id>/', RankListView.as_view(), name='ranks'),
    path('ranktypes/<int:rank_id>/', RankTypeListView.as_view(), name='ranktypes'),
    path('experts_lab/<int:lab_id>/',ExpertsInLab.as_view(), name='experts_lab'),
    path('experts_not_assigned/<int:lab_id>/',ExpertsNotAssignedToLab.as_view(), name='experts_not_assigned'),
    path('experts_lab/<int:lab_id>/expert/<int:expert_id>/delete/', RemoveExpertFromLab.as_view(),
         name='experts_lab_remove'),
    path('experts_lab/expert/create/', AddExpertToLab.as_view(),
         name='experts_lab_create'),



    path('ex_area_lab/<int:lab_id>/', ExpertiseAreaInLab.as_view(), name='ex_area_lab'),
    path('ex_area_lab/<int:lab_id>/permission/<int:permission_id>/delete/', RemoveExpertiseAreaFromLab.as_view(),
         name='permission_lab_remove'),



]

mvdaisy/expert/urls.py
from django.urls import path

from expert.views import (
    ExpertView,
    AddExpertView,
    ExpertListView,
    EditExpertView,
    ExpertDelete,
    custom_edit_expert,
    laboratory_edit,
    LabsListView,
    LabEditView,
    CustomCreateExpert,
)
app_name = "expert"
urlpatterns = [
    path("", ExpertListView.as_view(), name="expert_list"),
    path("add_expert/", AddExpertView.as_view(), name="expert_add"),
    path("edit_expert/<int:pk>/", EditExpertView.as_view(), name="expert_edit"),
    path("expert/<int:pk>/", ExpertView.as_view(), name="expert"),
    path("expert_delete/<int:pk>/", ExpertDelete.as_view(), name="expert_delete"),
    path("custom_edit/", CustomCreateExpert.as_view(), name="custom_edit"),
    path("laboratory_edit/", laboratory_edit, name="laboratory_edit"),
    path("labs/", LabsListView.as_view(), name="labs"),
    path("lab_edit/<int:pk>/", LabEditView.as_view(), name="lab_edit"),


]

mvdaisy/mvdaisy/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from debug_toolbar.toolbar import debug_toolbar_urls
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),

    re_path('^auth/', include('djoser.urls')),
    re_path('^auth/', include('djoser.urls.authtoken')),


    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/docs/', SpectacularSwaggerView.as_view(url_name='schema'), name='docs'),

    path('', include("main.urls", namespace="main")),
    path('experts/', include("expert.urls", namespace="experts")),
    path('', include("users.urls", namespace="users")),
    path('exps/', include("expertizes.urls", namespace="expertizes")),

    path('api/', include("api.urls")),



] + debug_toolbar_urls()

mvdaisy/expert/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy

Expert = get_user_model()


class Laboratory(models.Model):
	name = models.CharField(max_length=100, verbose_name="Название лаборатории")
	experts = models.ManyToManyField(Expert, related_name='laboratories', through="ExpertLaboratory")

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse_lazy("experts:lab_edit", kwargs={'pk': self.pk})

	class Meta:
		verbose_name = "Лаборатория"
		verbose_name_plural = "Лаборатории"


class ExpertiseArea(models.Model):
	name = models.CharField(max_length=100, verbose_name="Название допуска")
	experts = models.ManyToManyField(Expert, through="ExpertExpertiseArea", related_name="expertiseareas")
	laboratory = models.ForeignKey(Laboratory, on_delete=models.CASCADE, related_name="expertiseareas")

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = "Допуск"
		verbose_name_plural = "Допуска"


class ExpertExpertiseArea(models.Model):
	expert = models.ForeignKey(Expert, on_delete=models.CASCADE, related_name="expert_expertisearea")
	expertisearea = models.ForeignKey(ExpertiseArea, on_delete=models.CASCADE, related_name="expert_expertisearea")
	start_date = models.DateField(null=True, blank=True,  verbose_name="Дата начала допуска")
	end_date = models.DateField(null=True, blank=True, verbose_name="Дата окончания допуска")

	class Meta:
		verbose_name = "Эксперт-допуск"
		verbose_name_plural = "Эксперт-допуск"


class ExpertLaboratory(models.Model):
	expert = models.ForeignKey(Expert, on_delete=models.CASCADE, related_name="expert_laboratory")
	laboratory = models.ForeignKey(Laboratory, on_delete=models.CASCADE, related_name="expert_laboratory")
	start_date = models.DateField(null=True, blank=True, verbose_name="Начало работы в лаборатории")
	end_date = models.DateField(null=True, blank=True,  verbose_name="Конец работы в лаюоратории")

mvdaisy/main/models.py
from django.db import models
from django.db.models import UniqueConstraint


class Rank(models.Model):
	"""
	Звание: майор, лейтенант, служащий
	"""
	name = models.CharField(max_length=100, verbose_name="Имя")

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = "Звание"
		verbose_name_plural = "Звания"


class RankType(models.Model):
	"""Тип звания: полиции, юстиции, внутренней службы """
	name = models.CharField(max_length=100, verbose_name="Имя")
	ranks = models.ManyToManyField(Rank, related_name="types", through="RankAndType")

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = "Тип звания"
		verbose_name_plural = "Типы званий"


class RankAndType(models.Model):
	rank = models.ForeignKey(Rank, on_delete=models.PROTECT, related_name="linked_type")
	type = models.ForeignKey(RankType, on_delete=models.PROTECT, related_name="linked_rank")

	class Meta:
		constraints = [
			UniqueConstraint(fields=("rank", "type"), name='rank_type_constraint')
		]

	def __str__(self):
		return self.rank.name + " " + self.type.name


class Position(models.Model):
	"""Должность"""
	name = models.CharField(max_length=100, verbose_name="Имя")

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = "Должность"
		verbose_name_plural = "Должности"

mvdaisy/expert/forms.py
from django import forms
from django.forms import inlineformset_factory
from main.models import Rank, RankType
from expert.models import Laboratory, ExpertiseArea
from users.models import Expert



class RankTypeLink(forms.Form):
	type_qs = RankType.objects.all()
	type = forms.ModelChoiceField(type_qs, label="Тип звания")

	rank_qs = Rank.objects.all()
	rank = forms.ModelChoiceField(rank_qs, label="Звание")


class ExpertForm(forms.ModelForm):

	class Meta:
		model = Expert
		fields = ["first_name", "second_name", "last_name", "sex", "working", "rank", "rank_type", "position",]


class ExpertiseAreaForm(forms.ModelForm):
	name = forms.ModelChoiceField(ExpertiseArea.objects.all())
	class Meta:
		model = ExpertiseArea
		fields = ["name"]



PermissionLaboratoryFormSet = inlineformset_factory(Laboratory, ExpertiseArea, form=ExpertiseAreaForm, fields=("name",), extra=3, can_delete=True)

mvdaisy/expert/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, FileResponse
from django.db.models import Window, Count, ProtectedError, OuterRef, Subquery, Prefetch
from django.db.models.functions import RowNumber
from django.urls import reverse_lazy
from django.views.decorators.http import require_http_methods
from django.views.generic import DetailView, UpdateView, ListView, DeleteView, CreateView
from django.forms.models import model_to_dict
from django.core.handlers.wsgi import WSGIRequest
from django.utils.timezone import make_aware

from users.models import Expert
from main.models import RankAndType, RankType, Rank
from expert.models import ExpertLaboratory, ExpertExpertiseArea, Laboratory, ExpertiseArea
from expert.forms import RankTypeLink, ExpertForm, PermissionLaboratoryFormSet


def index(request):
    return HttpResponse("Начало разработки")


class ExpertListView(ListView):
    model = Expert
    template_name = "expert/expert_list.html"
    extra_context = {"active": "experts"}

    def get_queryset(self):
        return Expert.objects.select_related("rank", "rank_type", "position")


class AddExpertView(CreateView):
    model = Expert
    template_name = "expert/expert_add.html"
    fields = ["username", "last_name", "first_name", "second_name",  "sex",  "birth_date",  "rank", "rank_type", "position"]
    success_url = reverse_lazy("experts:expert_list")



class EditExpertView(UpdateView):
    model = Expert
    template_name = "expert/expert_add.html"
    fields = ["last_name", "first_name", "second_name", "sex", "birth_date", "rank", "rank_type", "position"]
    success_url = reverse_lazy("experts:expert_list")

    def get(self, request, *args, **kwargs):
        print("anus")
        return super().get(request, *args, **kwargs)


class ExpertView(DetailView):
    model = Expert
    template_name = "expert/expert_detail/index.html"


    def get_object(self, queryset=None):
        pk = self.kwargs.get(self.pk_url_kwarg)
        obj = (
            self.model.objects
            .filter(pk=pk)
            .select_related("rank", "rank_type", "position")
        )
        perm_rel = Prefetch("expert_expertisearea",
                            queryset=ExpertExpertiseArea.objects.select_related("expertisearea"))
        lab_rel = Prefetch("expert_laboratory", queryset=ExpertLaboratory.objects.select_related("laboratory"))
        obj = obj.prefetch_related(perm_rel, lab_rel)
        obj = obj.first()
        return obj

    def _table_with_header(self, parent, child:str, title:str=""):
        table = {"title": f"{title.capitalize()}:",
                 "header": {"name": "Название", "start_date": "Начало", "end_date": "Конец"}
        }
        data = []
        for item in parent.all():
            item_dict = {"name": getattr(item, child).name, "start_date":item.start_date, "end_date": item.end_date}
            data.append(item_dict)
        table["data"] = data
        return table


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        expert = {
            "fio": f"{self.object.last_name} {self.object.first_name} {self.object.second_name}",
            "sex": "мужской" if self.object.sex else "женский",
            "rank": f"{self.object.rank.name} {self.object.rank_type.name}",
            "position": self.object.position.name,
        }

        laboratories = self._table_with_header(self.object.expert_laboratory, "laboratory", "лаборатории")
        permissions = self._table_with_header(self.object.expert_expertisearea, "expertisearea", "допуска")
        context.update({"expert": expert, "laboratories": laboratories, "permissions": permissions})
        return context




class ExpertDelete(DeleteView):
    model = Expert
    success_url = reverse_lazy("experts:expert_list")
    template_name = "expert/expert_delete.html"


def custom_edit_expert(request):
    form = ExpertForm()
    context = {"form": form}
    return render(request, "expert/expert_custom_edit.html", context)


class CustomCreateExpert(CreateView):
    model = Expert
    form_class = ExpertForm

    template_name = "expert/expert_custom_edit.html"
    success_url = reverse_lazy("experts:expert_list")



def laboratory_edit(request):
    """
    Здесь можно реализовать ввод через Formset: в одной лвборатории несколько направлений
    :param request:
    :return:
    """
    lab = Laboratory.objects.get(pk=2)
    if request.method =="POST":
        formset = PermissionLaboratoryFormSet(request.POST, instance=lab)
        if formset.is_valid():
            formset.save()
            return redirect("expert_list")
    else:
        formset = PermissionLaboratoryFormSet(instance=lab)
    context = {"formset": formset, "laboratory": lab}
    return render(request, "expert/laboratory_edit.html", context=context)

class LabsListView(ListView):
    extra_context = {"active": "laboratories"}
    template_name = "expert/labs.html"
    model = Laboratory

class LabEditView(DetailView):
    template_name = "expert/lab_edit.html"

    def get_queryset(self):
        pk = self.kwargs['pk']
        # query = Laboratory.objects.filter(pk=pk).prefetch_related("experts")
        query = Laboratory.objects.prefetch_related(Prefetch("experts", queryset=Expert.objects.distinct()), "expertiseareas")
        return query

mvdaisy/expert/templates/expert/chained.html
{% extends "base.html" %} 
{% block content %} 
<form>
<select id="types" name="rank-type" hx-get="{% url 'chained_rank' %}" hx-target="#ranks" hx-swap="outerHTML">
<option value="" selected> тип звания</option>
{% for t in types %}
<option value="{{t.pk}}">{{t.name}}</option>
{% endfor %}
</select>

{% include "daisy/partial/rank_select.html" %} 
</form>

{% endblock content %}

mvdaisy/expert/templates/expert/expert_add.html
{% extends "base.html" %}
{% block content %}
<div class="list_row section_title section_colors">Новый эксперт:</div>

PK:{{pk}}
<form method="post">
  {% csrf_token %} 
  {% for field in form %}
  <div class="row_content row_grid_2">
    <div>{{field.label}}</div> <div>{{field}}</div>
  </div>
  {% endfor %}
  <button type="submit"  class="row-button">Добавить</button>
</form>
{% endblock content %}

mvdaisy/expert/templates/expert/expert_create.html
{% extends "base.html" %} 
{% block content %} 

<form action="" method="post">
    {% csrf_token %}
<div class="flex justify-start gap-1 align-middle">
    <label for="exp_first_name" class="w-44">{{form.first_name.label}}</label>
    <input id="exp_first_name"  class="m-2 w-40 border-2" type="text"/>
</div>
<div class="flex justify-start gap-1 align-middle">
    <label for="exp_second_name" class="w-44">{{form.second_name.label}}</label>
    <input id="exp_second_name"  class="m-2 w-40 border-2" type="text"/>
</div>
<div class="flex justify-start gap-1 align-middle">
    <label for="exp_last_name" class="w-44">{{form.last_name.label}}</label>
    <input id="exp_last_name"  class="m-2 w-40 border-2" type="text"/>
</div>
<div class="flex justify-start gap-1 align-middle">
    <label for="exp_last_name" class="w-44">{{form.sex.label}}</label>
    <input id="exp_last_name" name= class="m-2 w-40 border-2" type="text"/>
</div>

<button class="m-2 w-40 border-2">Создать<button>
</form>
{% endblock content %}

mvdaisy/expert/templates/expert/expert_custom_edit.html
{% extends "base.html" %}

{% block content %}
<h2>редактирование эксперта</h2>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
<input type="submit" value="Отправить" />
</form>
{% endblock content %}

mvdaisy/expert/templates/expert/expert_datail.html
{% extends "base.html" %}
{% block content %}
    <div>    
        <div class="list_row section_title section_colors">Личные данные:</div>
        <div class="row_content row_grid_2">
            <div>ФИО</div><div>{{ expert.fio }}</div>
        </div>
        <div class="row_content row_grid_2">
            <div>Пол</div><div>{{expert.sex}}</div>
        </div>
            <div class="row_content row_grid_2">
            <div>Звание</div><div>{{expert.rank}}</div>
        </div>
            <div class="row_content row_grid_2">
            <div>Должность</div><div>{{expert.position}}</div>
        </div>        
    </div>    

    {% include 'expert/expert_detail_section.html' with data=laboratories %}    
    {% include 'expert/expert_detail_section.html' with data=permissions %}




{% endblock content %}

mvdaisy/expert/templates/expert/expert_delete.html
{% extends "base.html" %}
{% block content %}
<div class="title">Точно удалить эксперта "{{ object }}"?</div>
<div>
<form method="post">
  {% csrf_token %}
  <div class="row_content row_grid_2">
    <button  class="row-button"
      type="button"
      onclick="window.location.href = `{% url 'experts:expert_list' %}`;"
    >
      Омена
    </button>
    <button class="row-button" type="submit">Удалить</button>
  </div>
</form>
</div>
{% endblock content %}

mvdaisy/expert/templates/expert/expert_detail_section.html
<div>
    <div class="list_row section_title section_colors">{{data.title}}</div>
    <div class="row_content row_grid_3 section_colors section_header">
        {% for column in data.header.values %}
            <div>{{column}}</div>
        {% endfor %}
    </div>
    {% for row in data.data %}
        <div class="row_content row_grid_3">
            <div>{{row.name}}</div><div>{{row.start_date}}</div><div>{{row.end_date|default:"-"}}</div>
        </div>
    {% endfor %}
</div>

mvdaisy/expert/templates/expert/expert_list.html
{% extends "base.html" %}
{% block content %}
<div class="title">Здесь будет список экспертов</div>
<a
  href="{% url 'experts:expert_add' %}"
  >Добавить эксперта</a>

<div class="w-[960px] my-2 mx-auto">
  {% for item in object_list %}
  <div class="list_row row_content">
    {{item.first_name}} {{item.last_name}} {{item.position}} {{item.rank}}
    {{item.rank_type}}

      <div class="button_block">
          <form action="{% url 'experts:expert' item.pk %}">
            <button
              class="row-button">
              Инфо
            </button>
          </form>

          <form action="{% url 'experts:expert_edit' item.pk %}">
            <button
              class="row-button">
              Редактировать
            </button>
          </form>

          <form action="{% url 'experts:expert_delete' item.pk %}">
            <button
              class="row-button">
              Удалить
            </button>
          </form>
      </div>
  </div>
  {% endfor %}
  <p><a class="h-10 underline to-blue-700" href="{% url 'experts:custom_edit' %}">Редактирование отдельного эксерта</a></p>
  <p><a class="h-10 underline to-blue-700" href="{% url 'experts:laboratory_edit' %}">Редактирование лаборатории</a></p>
</div>
{% endblock content %}

mvdaisy/expert/templates/expert/lab_edit.html
{% extends "base.html" %}
{% load static %}
{% block content %} 
<div  class="list_row section_title section_colors" id="lab-title" data-id="{{object.id}}">Лаборатория: {{object.name}}</div>
-----------
{% comment %}
{% for expert in object.experts.all %}
    <div>{{ expert.last_name }} {{ expert.first_name }}</div>
{%endfor%}

{% for area in object.expertiseareas.all %}
    <div>{{ area.name }}</div>
{%endfor%} {% endcomment %}

<div id ="experts-section" ></div>
<div><button class ="row-button" style="margin: 10px 0; width: 200px" id="add-expert-button">Добавить эксперта</button></div>
-----------
<div id ="permissions-section" ></div>
<div><button  class ="row-button" style="margin: 10px 0; width: 200px" id="add-permission-button">Добавить допуск</button></div>

{#==============================#}
<div id="id-modal-expert" class="modal">
    <div class="modal-content">
        <div class="modal-header">
            <h2>Выберете эксперта</h2>
        </div>
        <div class="modal-body">
        </div>
        <div class="modal-footer">
            <button class="row-button" id="confirm-expert-button">Подтвердить</button>
        </div>
    </div>
</div>


{#==============================#}
<div id="id-modal-permission" class="modal">
    <div class="modal-content">
        <div class="modal-header">
            <h2>Выберете допуск</h2>
        </div>
        <div class="modal-body">
            <p>Some text in the Modal Body</p>
            <p>Some other text...</p>
            <p>Больше допусков</p>
            <p>Еще больше допусков</p>
        </div>
        <div class="modal-footer">
            <button class="row-button" id="confirm-permission-button">Подтвердить</button>
        </div>
    </div>
</div>

{% endblock content %}
{% block scripts %}
    {{block.super }}
    <script type="module" src="{% static 'expert/js/process-lab-form.js' %}"></script>
{% endblock scripts %}

mvdaisy/expert/templates/expert/laboratory_edit.html
{% extends "base.html" %}
{% block content %}
<h2>Допуска в лаборатории {{laboratory.name}}</h2>
<form method="post">
  {% csrf_token %} 
    {{ formset.management_form }}
    <table>
        {% for form in formset %}
            <tr>
                {{ form }}
            </tr>
        {% endfor %}
    </table>
    <button type="submit">Сохранить</button>
</form>
{% endblock content %}

mvdaisy/expert/templates/expert/labs.html
{% extends "base.html" %}
{% block content %} 
<div class="title">Список лабораторий</div>
{% for lab in object_list %}
  <div class="list_row row_content">
    {# <a href="{% url 'expert:lab_edit' lab.pk %}"> #}
        <a href="{{ lab.get_absolute_url  }}">
      {{lab.name}}
    </a>
  </div>
{% endfor %}
{% endblock content %}

mvdaisy/expert/templates/expert/link_rank_type.html
{% block content %} 
  {% include "daisy/partial/rank_type_form.html" %}
  <hr class="my-2" />
  {% include "daisy/partial/rank_list.html" %} 
{% endblock content %}