mvdaisy/api/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import (CustomUserViewSet,
                    ExpertsView,
                    ExpertRetriveView,
                    RankListView,
                    RankTypeListView,
                    ExpertsInLab,
                    ExpertiseAreaInLab,
                    RemoveExpertFromLab,
                    RemoveExpertiseAreaFromLab,
                    ExpertsNotAssignedToLab,
                    AddExpertToLab,
                    )

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', CustomUserViewSet)


urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    path('experts/<int:pk>/', ExpertRetriveView.as_view(), name='expert'),
    path('experts/', ExpertsView.as_view(), name='experts'),
    path('ranks/<int:type_id>/', RankListView.as_view(), name='ranks'),
    path('ranktypes/<int:rank_id>/', RankTypeListView.as_view(), name='ranktypes'),
    path('experts_lab/<int:lab_id>/',ExpertsInLab.as_view(), name='experts_lab'),
    path('experts_not_assigned/<int:lab_id>/',ExpertsNotAssignedToLab.as_view(), name='experts_not_assigned'),
    path('experts_lab/<int:lab_id>/expert/<int:expert_id>/delete/', RemoveExpertFromLab.as_view(),
         name='experts_lab_remove'),
    path('experts_lab/expert/create/', AddExpertToLab.as_view(),
         name='experts_lab_create'),



    path('ex_area_lab/<int:lab_id>/', ExpertiseAreaInLab.as_view(), name='ex_area_lab'),
    path('ex_area_lab/<int:lab_id>/permission/<int:permission_id>/delete/', RemoveExpertiseAreaFromLab.as_view(),
         name='permission_lab_remove'),



]

mvdaisy/expert/urls.py
from django.urls import path

from expert.views import (
    ExpertView,
    AddExpertView,
    ExpertListView,
    EditExpertView,
    ExpertDelete,
    custom_edit_expert,
    laboratory_edit,
    LabsListView,
    LabEditView,
    CustomCreateExpert,
)
app_name = "expert"
urlpatterns = [
    path("", ExpertListView.as_view(), name="expert_list"),
    path("add_expert/", AddExpertView.as_view(), name="expert_add"),
    path("edit_expert/<int:pk>/", EditExpertView.as_view(), name="expert_edit"),
    path("expert/<int:pk>/", ExpertView.as_view(), name="expert"),
    path("expert_delete/<int:pk>/", ExpertDelete.as_view(), name="expert_delete"),
    path("custom_edit/", CustomCreateExpert.as_view(), name="custom_edit"),
    path("laboratory_edit/", laboratory_edit, name="laboratory_edit"),
    path("labs/", LabsListView.as_view(), name="labs"),
    path("lab_edit/<int:pk>/", LabEditView.as_view(), name="lab_edit"),


]

mvdaisy/main/urls.py
from django.urls import path
from main.views import ExpertListView, RanksView

app_name = "main"
urlpatterns = [
    path("", ExpertListView.as_view(), name="index"),
    path("ranks/", RanksView.as_view(), name="ranks"),
]

mvdaisy/mvdaisy/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from debug_toolbar.toolbar import debug_toolbar_urls
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),

    re_path('^auth/', include('djoser.urls')),
    re_path('^auth/', include('djoser.urls.authtoken')),


    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/docs/', SpectacularSwaggerView.as_view(url_name='schema'), name='docs'),

    path('', include("main.urls", namespace="main")),
    path('experts/', include("expert.urls", namespace="experts")),
    path('', include("users.urls", namespace="users")),
    path('exps/', include("expertizes.urls", namespace="expertizes")),

    path('api/', include("api.urls")),



] + debug_toolbar_urls()

mvdaisy/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import LoginUser, LogoutUser



app_name = "users"
urlpatterns = [
    path("login/", LoginUser.as_view(), name="login_user"),
    # path("logout/", LogoutView.as_view(next_page='login_user'), name="logout_user"),
    path("logout/", LogoutUser.as_view(), name="logout_user"),


]

mvdaisy/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {% load static %}
        <script src="{% static '/js/test.js' %}"></script>
        <link
        rel="stylesheet"
        type="text/css"
        href="{% static '/css/style.css' %}"
        />
        <title>
        {% block title %} {% endblock title %}
        </title>
    </head>
    <body>
        <div class="header">
            <nav class="header__row">
                <div class="links_block">
                    <div {% if active == "main" %} class="option_active"  {% endif %} ><a href="{% url 'main:index' %}">Главная</a></div>
                    <div {% if active == "experts" %} class="option_active"  {% endif %} ><a href="{% url 'experts:expert_list' %}">Эксперты</a></div>
                    <div {% if active == "expertizes" %} class="option_active"  {% endif %} ><a href="{% url 'expertizes:index' %}">Экспертизы</a></div>
                    <div {% if active == "laboratories" %} class="option_active"  {% endif %} ><a href="{% url 'experts:labs' %}">Лаборатории</a></div>
                    <div {% if active == "ranks" %} class="option_active"  {% endif %} ><a href="{% url 'main:ranks' %}">Звания</a></div>
                    <div><a href="{% url 'admin:index' %}">Админка</a></div>
                </div>
            
            
                <div class="user_block">
                    {% if user.username%}
                     <div><a href="#"><span>{{user.first_name}} {{user.last_name}}</span></a></div>
                        
                        <form action="{% url 'users:logout_user' %}" method="POST">
                            {% csrf_token %}
                            <button class="row-button" type="submit">Выйти</button>
                        </form>
                    {% else%}
                        <form action="{% url 'users:login_user' %}" method="POST">
                            {% csrf_token %}
                            <button class="row-button" type="submit">Войти</button>
                        </form>

                    {% endif%}
                </div>
            </nav>
        </div>
        <div class="content">
            <div class="content__window">
                {% block content %} {% endblock content %}
            </div>
        </div>
        {% block scripts %} {% endblock scripts %}
    </body>
</html>